dateModified: 1783441286
email:
  fromEmail: dev@onedesigncompany.com
  fromName: 'Craft Starter'
  replyToEmail: null
  template: ''
  transportSettings:
    host: $SERVD_SMTP_HOSTNAME
    password: $SERVD_SMTP_PASSWORD
    port: $SERVD_SMTP_PORT
    useAuthentication: '1'
    username: $SERVD_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    23a06aab-c3b7-4b29-bcfb-ecdb987b69e9: 'Craft Starter' # Craft Starter
    439b957e-893e-4d96-ae87-cbd86af179c1: Common # Common
    911bd1d5-53ff-4a53-b9da-5546fba0a849: Default # Default
    c51820fb-df82-4cd2-b955-e6f381846903: 'Contact Form' # Contact Form
    e32fd166-977b-4969-8fd4-021cfac178cc: New # New
    f19c0ae7-fefa-45b3-aeee-297dea098f94: 'Public Schema' # Public Schema
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.6.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: APDWVN8BIKBEBSZ87OW6NGNQ
    schemaVersion: 3.4.12
  hyper:
    edition: standard
    enabled: true
    licenseKey: PCMO6NAVSO9ZXFCQE0K0A4RX
    schemaVersion: 1.0.0
  imager-x:
    edition: pro
    enabled: true
    licenseKey: 7S6C9R9P9RFDDNMHUK41Q3JZ
    schemaVersion: 4.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 5WE185Q05HKBPBAUBGUEZF1D
    schemaVersion: 3.0.13
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      disableDynamic: ''
      disableTransforms: ''
      fsMapsEnabled: ''
      imageAutoConversion: avif
      injectCors: ''
      projectSlug: ''
      securityKey: ''
      suppressWarnings: ''
      useLocalVolumes: false
  sherlock:
    edition: lite
    enabled: true
    schemaVersion: 5.1.0
    settings:
      apiKey: vgqpyjmjrzxlzqblfembetlitaajxoiu
      basicAuthEnabled: false
      basicAuthPassword: ''
      basicAuthUsername: ''
      blowfishHashCost:
        __assoc__:
          -
            - threshold
            - 13
      contentSecurityPolicy:
        __assoc__:
          -
            - canFail
            - true
      contentSecurityPolicySettings:
        __assoc__:
          -
            - enabled
            - false
          -
            - enforce
            - false
          -
            - header
            - true
          -
            - directives
            -
              -
                - 1
                - default-src
                - "'self'"
      cooldownDuration:
        __assoc__:
          -
            - threshold
            - 300
      cors:
        __assoc__:
          -
            - forceFail
            - true
      craftFilePermissions:
        __assoc__:
          -
            - canFail
            - true
      craftFolderPermissions:
        __assoc__:
          -
            - canFail
            - true
      craftFoldersAboveWebRoot:
        __assoc__:
          -
            - canFail
            - true
      criticalCraftUpdates:
        __assoc__:
          -
            - forceFail
            - true
      criticalPluginUpdates:
        __assoc__:
          -
            - forceFail
            - true
      defaultDirMode:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 509
      defaultFileMode:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 436
      defaultTokenDuration:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 86400
      devMode:
        __assoc__:
          -
            - forceFail
            - true
      disabledTests: null
      elevatedSessionDuration:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 300
      enableCsrfProtection:
        __assoc__:
          -
            - canFail
            - true
      headerProtectionSettings:
        __assoc__:
          -
            - enabled
            - true
          -
            - headers
            -
              -
                - true
                - Referrer-Policy
                - no-referrer-when-downgrade
              -
                - true
                - Strict-Transport-Security
                - max-age=15552000
              -
                - true
                - X-Content-Type-Options
                - nosniff
              -
                - true
                - X-Frame-Options
                - SAMEORIGIN
              -
                - true
                - X-Xss-Protection
                - '1; mode=block'
      highSecurityLevel: false
      httpsControlPanel:
        __assoc__:
          -
            - forceFail
            - true
      httpsFrontEnd:
        __assoc__:
          -
            - forceFail
            - true
      integrationSettings: null
      invalidLoginWindowDuration:
        __assoc__:
          -
            - threshold
            - 3600
      maxInvalidLogins:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 5
      maxScans: 100
      monitor: false
      notificationEmailAddresses: dev@onedesigncompany.com
      phpComposerVersion:
        __assoc__:
          -
            - canFail
            - true
      phpVersion:
        __assoc__:
          -
            - canFail
            - true
          -
            - thresholds
            -
              __assoc__:
                -
                  - '8.2'
                  - '2027-01-01'
                -
                  - '8.3'
                  - '2028-01-01'
      preventUserEnumeration:
        __assoc__:
          -
            - canFail
            - true
      referrerPolicy:
        __assoc__:
          -
            - canFail
            - true
      rememberedUserSessionDuration:
        __assoc__:
          -
            - threshold
            - 12096004
      requireEmailVerification:
        __assoc__:
          -
            - canFail
            - true
      sanitizeSvgUploads:
        __assoc__:
          -
            - canFail
            - true
      sendPoweredByHeader:
        __assoc__:
          -
            - canFail
            - false
      strictTransportSecurity:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 15552000
      testToEmailAddress:
        __assoc__:
          -
            - canFail
            - true
      translationDebugOutput:
        __assoc__:
          -
            - canFail
            - true
      useSecureCookies:
        __assoc__:
          -
            - canFail
            - true
      userSessionDuration:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 3600
      verificationCodeDuration:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 86400
      webAliasInSiteBaseUrl:
        __assoc__:
          -
            - forceFail
            - true
      webAliasInVolumeBaseUrl:
        __assoc__:
          -
            - forceFail
            - true
      xContentTypeOptions:
        __assoc__:
          -
            - canFail
            - true
      xFrameOptions:
        __assoc__:
          -
            - canFail
            - true
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'One Craft Starter'
  retryDuration: null
  schemaVersion: 5.10.0.0
  timeZone: America/Chicago
