dateModified: 1741366273
email:
  fromEmail: dev@onedesigncompany.com
  fromName: 'Craft Starter'
  replyToEmail: null
  template: ''
  transportSettings:
    host: $SERVD_SMTP_HOSTNAME
    password: $SERVD_SMTP_PASSWORD
    port: $SERVD_SMTP_PORT
    useAuthentication: '1'
    username: $SERVD_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    0d1c338d-da32-4a10-88f4-f030b2e38530: Simple # Simple
    23a06aab-c3b7-4b29-bcfb-ecdb987b69e9: 'Craft Starter' # Craft Starter
    439b957e-893e-4d96-ae87-cbd86af179c1: Common # Common
    911bd1d5-53ff-4a53-b9da-5546fba0a849: Default # Default
    c51820fb-df82-4cd2-b955-e6f381846903: 'Contact Form' # Contact Form
    e32fd166-977b-4969-8fd4-021cfac178cc: New # New
    f19c0ae7-fefa-45b3-aeee-297dea098f94: 'Public Schema' # Public Schema
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  hyper:
    edition: standard
    enabled: true
    licenseKey: 9BATK7KQ68NND6QUWAM0SKF4
    schemaVersion: 1.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: NKDDI9I1H4YW7F1HD0H8WOT1
    schemaVersion: 4.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: SN3FM9DHGRNVKRS8U0Q6I9X2
    schemaVersion: 3.0.12
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'One Craft Starter'
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
