dateModified: 1660247518
email:
  fromEmail: brian@onedesigncompany.com
  fromName: 'Craft Starter'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    23a06aab-c3b7-4b29-bcfb-ecdb987b69e9: Primary # Primary
    439b957e-893e-4d96-ae87-cbd86af179c1: Common # Common
    911bd1d5-53ff-4a53-b9da-5546fba0a849: Default # Default
    ffe220d8-2d21-4ccf-97f6-de256bcf34fb: 'Public Schema' # Public Schema
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  blitz:
    edition: standard
    enabled: true
    licenseKey: ZCZZPY7AIA8L73K89TRD4012
    schemaVersion: 4.2.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  environment-label:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 220GG8BTXE76LKQF6P7OZ47W
    schemaVersion: 3.0.11
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Starter'
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
