columnSuffix: null
handle: navigation
instructions: null
name: Navigation
searchable: false
settings:
  createButtonLabel: 'New nav item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - d25d6dcb-ab5c-4685-a616-bd5648b63d9e # Nav Item
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
