columnSuffix: null
handle: newsTags
instructions: null
name: Tags
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a tag'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:a58d8e41-03e5-4d79-a6aa-aae6f706fa6b' # News Tags
  targetSiteId: null
  validateRelatedElements: true
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
