columnSuffix: null
handle: teamMembers
instructions: null
name: 'Team Members'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a person'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:f091b4ec-a345-4b02-98c7-d35cfe1cca89' # People
  targetSiteId: null
  validateRelatedElements: true
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
