tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-03-07T12:29:26-06:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 982b8a9b-eb87-45ab-8514-53e4e8eaad3a
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-03-07T12:29:26-06:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 18e5199e-25dc-4cd3-b874-235eaae346c3
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-03-07T12:29:26-06:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 62abf081-6777-4fb1-91e4-9fea7763aca6
        userCondition: null
        warning: null
    name: Content
    uid: 657d1ebf-fd8f-43dc-b5e9-a00774242540
    userCondition: null
